add update-return-session

diff --git a/rootfs/usr/bin/plasma-session-oneshot b/rootfs/usr/bin/plasma-session-oneshot
--- a/rootfs/usr/bin/plasma-session-oneshot
+++ b/rootfs/usr/bin/plasma-session-oneshot
@@ -2,19 +2,24 @@
 
 set -e
 
-die() { echo >&2 "!! $*"; exit 1; }
+die() {
+  echo >&2 "!! $*"
+  exit 1
+}
+
+SESSION_FILE="/etc/lightdm/lightdm.conf.d/10-chimeraos-session.conf"
 
 SENTINEL_FILE="steamos-session-select"
 RETURN_SESSION_FILE="chimeraos-session-return"
 
 # If we proceed, execute this
-CHAINED_SESSION="/usr/bin/startplasma-wayland"
+# CHAINED_SESSION="/usr/bin/startplasma-wayland"
+CHAINED_SESSION="/usr/bin/startx /usr/bin/startplasma-x11"
 # If we decide the sentinel is consumed, execute this command instead and fail
 RESTORE_SESSION=(/usr/lib/os-session-select) # No arguments restores the session
 
 # Find or check config return session
-function check_return()
-{
+function check_return() {
   if [[ -z ${HOME+x} ]]; then
     echo >&2 "$0: No \$HOME variable!"
     # Rather than break we'll just launch plasma and hope for the best?
@@ -26,12 +31,12 @@ function check_return()
     cd "$config_dir"
     revert_value="$(cat "$RETURN_SESSION_FILE")"
     case "$revert_value" in
-      gamescope-session-opengamepadui|gamescope-session-steam-plus|gamescope-session-steam)
-        echo "$revert_value"
-        ;;
-      *)
-        echo "gamescope-session-steam"
-        ;;
+    gamescope-session-opengamepadui | gamescope-session-steam-plus | gamescope-session-steam)
+      echo "$revert_value"
+      ;;
+    *)
+      echo "gamescope-session-steam"
+      ;;
     esac
     rm "$RETURN_SESSION_FILE"
   ) || return 1 # If we couldn't read the value or it wasn't what we wanted
@@ -41,8 +46,7 @@ function check_return()
 }
 
 # Find or check config sentinel
-function check_sentinel()
-{
+function check_sentinel() {
   if [[ -z ${HOME+x} ]]; then
     echo >&2 "$0: No \$HOME variable!"
     # Rather than break we'll just launch plasma and hope for the best?
@@ -55,7 +59,8 @@ function check_sentinel()
     cd "$config_dir"
     sentinel_value="$(cat "$SENTINEL_FILE")"
     if [[ "$sentinel_value" == "wayland" ]]; then
-      echo "/usr/bin/startplasma-wayland"
+      # echo "/usr/bin/startplasma-wayland"
+      echo "/usr/bin/startx /usr/bin/startplasma-x11"
     else
       return 1
     fi
@@ -67,10 +72,26 @@ function check_sentinel()
   return 0
 }
 
+function delay_set_return_session() {
+  # Check if 'at' is installed
+  if ! command -v at &> /dev/null; then
+    echo "'at' command not found. Please install 'at' first."
+    return 0
+  fi
+
+  # Schedule the command to run after 5 seconds
+  echo "echo -e \"[Seat:*]\nautologin-session=$1\" > $SESSION_FILE" | sudo at now + 1 minutes
+}
+
 if CONFIGURED_CHAINED_SESSION=$(check_sentinel); then
   # We found and consumed the oneshot sentinel, proceed to launch plasma
   echo >&2 "$0: Found and removed sentinel file for one-shot desktop, proceeding to launch"
-  exec "$CONFIGURED_CHAINED_SESSION"
+  return_file="$HOME/.config/${RETURN_SESSION_FILE}"
+  return_session=$(cat "$return_file")
+  # echo "RETURN_SESSION: $cat($HOME/.config/${RETURN_SESSION_FILE})" >> $HOME/session.log
+  # exec "$CONFIGURED_CHAINED_SESSION"
+  delay_set_return_session $return_session || true
+  sudo chimera-session-use-lightdm plasmax11
 else
   if CONFIGURED_RETURN_SESSION=$(check_return); then
     /usr/lib/os-session-select "$CONFIGURED_RETURN_SESSION"
